[[main]]
  identifier = "home"
  pre = ""
  post = ""
  name = "Home"
  url = "/"
  title = ""
  weight = 1
[[main]]
  identifier = "news"
  pre = ""
  post = ""
  name = "News"
  url = "/news/"
  title = ""
  weight = 2
[[main]]
  identifier = "navigation"
  pre = ""
  post = ""
  name = "Navigation"
  url = "/navigation/"
  title = ""
  weight = 3
[[main]]
  identifier = "games"
  pre = ""
  post = ""
  name = "Play to Earn"
  url = "/games/"
  title = ""
  weight = 4
[[main]]
  identifier = "community"
  pre = ""
  post = ""
  name = "Community"
  url = "/community/activities/a/"
  title = ""
  weight = 5
  
[[community]]
  name = "Activities"
  weight = 1
  identifier = "activities"
  url = "/community/activities/"
[[community]]
  name = "Famland Metaverse"
  weight = 2
  identifier = "famland-metaverse"
  url = "/community/famland-metaverse/"
