
# 页面底部信息配置
[footer]
enable = true
#  自定义内容 (支持 HTML 格式)
custom = ''
#  是否显示 Hugo 和主题信息
hugo = true
#  托管服务信息 (支持 HTML 格式)
# <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>
hostedOn = '' 
#  是否显示版权信息
copyright = true
#  是否显示作者
author = true
# 网站创立年份
since = 2019
# ICP 备案信息, 仅在中国使用 (支持 HTML 格式)
icp = ""
# 许可协议信息 (支持 HTML 格式)
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
[footer.zh]

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
[options]
	breadCrumb = true


